version: '3.7'
services:
    retroarch-web:
        image: retroarch
        build:
            context: .
            dockerfile: Dockerfile
        container_name: retroarch
        volume:
            - ~/retroarch:/var/www/html/assets/cores/retroarch
        ports:
            - '8080:80'
        restart: unless-stopped
