version: '3.7'
services:
    retroarch-web:
        image: retroarch
        build:
            context: .
            dockerfile: Dockerfile
        container_name: retroarch
        ports:
            - '8080:80'
