name: Build start RetroArch Web Games

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Build the Docker image
    - name: Build the Docker image
      run: docker build -t retroarch-web-games .

    # start the Docker container the container port 8080 is mapped to the host port 80
    - name: Start the Docker container
      run: docker run -d -p 80:8080 retroarch-web-games
